### ISSUE TITLE
How to enable SparseTensor option? 

### ISSUE THREAD

**Issue by GabbySuwichaya** [dongkwan-kim/SuperGAT#36]
Hi Dongkwan, I would like to ask how to use the SparseTensor option with our code. 
Also, do I have to write the message_and_propagate() myself ... Or your code already did that? 
Best,

**Comment by dongkwan-kim** [comment]
Hi, Gabby.

> I would like to ask how to use the SparseTensor option with our code.
> Also, do I have to write the message_and_propagate() myself ... Or your code already did that?

Currently, our code does not support SparseTensor, since several operations in SuperGAT (e.g., negative_sampling) do not take SparseTensor as an input.

Thank you.

**Comment by GabbySuwichaya** [comment]
Thank you. :)
