### ISSUE TITLE
deepcopy the SuperGAT model failed

### ISSUE THREAD

**Issue by qszhang-hub** [dongkwan-kim/SuperGAT#42]
when I tried to deepcopy the best model during validation, it failed.
my code is just like this:

    if val_acc > best_val_acc:
       best_val_acc = val_acc
       best_model = copy.deepcopy(model)   # the model is SuperGAT
My SuperGAT model：

    from torch_geometric.nn import SuperGATConv

    class SuperGAT(torch.nn.Module):
        def __init__(self, in_features, out_features, hidden_dim=8, heads=8, dropout_rate=0.6):
            super(SuperGAT, self).__init__()
            self.conv1 = SuperGATConv(in_features, hidden_dim, heads=heads, dropout=dropout_rate, attention_type='MX',
                                      edge_sample_ratio=0.8, is_undirected=True)
            self.conv2 = SuperGATConv(heads * hidden_dim, out_features, heads=heads, concat=False, dropout=dropout_rate,
                                      attention_type='MX', edge_sample_ratio=0.8, is_undirected=True)
            self.dropout = torch.nn.Dropout(dropout_rate)
            self.elu = nn.ELU(inplace=True)

        def forward(self, x, edge_index):
            x = self.dropout(x)
            x = self.conv1(x, edge_index)
            x = self.elu(x)
            att_loss = self.conv1.get_attention_loss()
            x = self.dropout(x)
            x = self.conv2(x, edge_index)
            att_loss += self.conv2.get_attention_loss()
            return x, att_loss

the error:

    RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment

**Comment by dongkwan-kim** [comment]
Sorry, this error is not reproducible in my environment... Can you give me a full context of your code?

**Comment by qszhang-hub** [comment]
OK.
Here is my code :
(note to adjust the location of the Cora dataset before running)

    from typing import Callable, Tuple
    import torch
    from torch_geometric.nn import SuperGATConv
    from torch import Tensor, nn
    from torch_geometric.data import Data
    from torch_geometric.datasets import Planetoid
    from torch_geometric.transforms import NormalizeFeatures
    from typing_extensions import Literal
    import copy
    
    
    # SuperGAT model
    class SuperGAT(torch.nn.Module):
        def __init__(self, in_features, out_features, hidden_dim=8, heads=8, dropout_rate=0.6):
            super(SuperGAT, self).__init__()
            self.conv1 = SuperGATConv(in_features, hidden_dim, heads=heads, dropout=dropout_rate, attention_type='MX',
                                      edge_sample_ratio=0.8, is_undirected=True)
            self.conv2 = SuperGATConv(heads * hidden_dim, out_features, heads=heads, concat=False, dropout=dropout_rate,
                                      attention_type='MX', edge_sample_ratio=0.8, is_undirected=True)
            self.dropout = torch.nn.Dropout(dropout_rate)
            self.elu = nn.ELU(inplace=True)
    
        def forward(self, x, edge_index):
            x = self.dropout(x)
            x = self.conv1(x, edge_index)
            x = self.elu(x)
            att_loss = self.conv1.get_attention_loss()
            x = self.dropout(x)
            x = self.conv2(x, edge_index)
            att_loss += self.conv2.get_attention_loss()
            return x, att_loss
    
    
    LossFn = Callable[[Tensor, Tensor], Tensor]
    Stage = Literal["train", "val", "test"]
    
    
    def train_step(model: torch.nn.Module, data: Data, optimizer: torch.optim.Optimizer, criterion: LossFn) \
            -> Tuple[float, float]:
        model.train()
        optimizer.zero_grad()
        mask = data.train_mask
        logits, att_loss = model(data.x, data.edge_index)
        logits = logits[mask]
        preds = logits.argmax(dim=1)
        y = data.y[mask]
        loss = criterion(logits, y)
        loss += 4.0 * att_loss
        acc = (preds == y).float().mean().item()
        loss.backward()
        optimizer.step()
        return loss.item(), acc
    
    
    @torch.no_grad()
    def eval_step(model: torch.nn.Module, data: Data, criterion: LossFn, stage: Stage) \
            -> Tuple[float, float]:
        model.eval()
        mask = getattr(data, f"{stage}_mask")
        logits, att_loss = model(data.x, data.edge_index)
        logits = logits[mask]
        preds = logits.argmax(dim=1)
        y = data.y[mask]
        loss = criterion(logits, y)
        acc = (preds == y).float().mean().item()
        return loss.item(), acc
    
    
    def train(model: torch.nn.Module,
              data: Data,
              optimizer: torch.optim.Optimizer,
              criterion: LossFn = torch.nn.CrossEntropyLoss(),
              max_epochs: int = 200,
              early_stopping: int = 20,
              print_interval: int = 10):
        best_val_acc = 0
        patience = 0
        best_model = None
        for epoch in range(1, max_epochs + 1):
            loss, acc = train_step(model, data, optimizer, criterion)  # train
            val_loss, val_acc = eval_step(model, data, criterion, "val")  # validate
    
            # save the best model
            if val_acc > best_val_acc:
                best_val_acc = val_acc
                best_model = copy.deepcopy(model)  # an error occurred here during runtime
                patience = 0
            else:
                patience += 1
            if patience == early_stopping:  # early stopping
                print("\nEarly stopping...")
                break
    
            if epoch % print_interval == 0:
                print(f"\nEpoch: {epoch}\n----------")
                print(f"Train loss: {loss:.4f} | Train acc: {acc:.4f}")
                print(f"  Val loss: {val_loss:.4f} |   Val acc: {val_acc:.4f}")
    
        test_loss, test_acc = eval_step(best_model, data, criterion, "test")  # test
    
        print(f"\nEpoch: {epoch}\n----------")
        print(f"Train loss: {loss:.4f} | Train acc: {acc:.4f}")
        print(f"  Val loss: {val_loss:.4f} |   Val acc: {val_acc:.4f}")
        print(f" Test loss: {test_loss:.4f} |  Test acc: {test_acc:.4f}")
    
    
    if __name__ == '__main__':
        MAX_EPOCHS = 300
        LEARNING_RATE = 0.01
        WEIGHT_DECAY = 5e-4
        EARLY_STOPPING = 20
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    
        # load Cora
        dataset = Planetoid("./Dataset", name='Cora', transform=NormalizeFeatures())
        data = dataset[0]
    
        data = data.to(device)
        model = SuperGAT(dataset.num_node_features, dataset.num_classes)
        model = model.to(device)
        optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE, weight_decay=WEIGHT_DECAY)
        train(model, data, optimizer, max_epochs=MAX_EPOCHS, early_stopping=EARLY_STOPPING)

**Comment by dongkwan-kim** [comment]
I see. This will solve your problem: removing tensors that are not created by the user.

```python
            del model.conv1.att_x
            del model.conv1.att_y
            del model.conv2.att_x
            del model.conv2.att_y
            best_model = copy.deepcopy(model)  # an error occurred here during runtime
```

**Comment by qszhang-hub** [comment]
:)
Thank you very much.
